-- ════════════════════════════════════════════════════════════
-- تساهيل العمرة — بيانات أولية (seed). شغّله بعد schema.sql.
-- (اختياري: التطبيق يعبّئ تلقائياً عند أول دخول إذا كانت الجداول فارغة.)
-- ════════════════════════════════════════════════════════════

-- hotels (4)
insert into hotels (id, doc) values ('HTL-001', '{"id":"HTL-001","name":"دار الإيمان جراند","city":"مكة","stars":4,"distanceM":500,"district":"أجياد","phone":"+966 12 543 7777","mapUrl":"","status":"active","notes":"","features":[{"id":"f1","icon":"wifi","text":"واي فاي مجاني"},{"id":"f2","icon":"breakfast","text":"إفطار مجاني"},{"id":"f3","icon":"pool","text":"مسبح"},{"id":"f4","icon":"parking","text":"موقف سيارات"}],"roomTypes":[{"id":"r1","kind":"private","beds":1,"pricePerNight":280},{"id":"r2","kind":"shared","beds":3,"pricePerNight":110}],"tasaheelNote":"فندق ممتاز وقريب جداً من الحرم — يُنصح للعائلات.","reviews":[{"id":"rv1","name":"خالد","text":"تجربة رائعة والخدمة ممتازة","consent":true}]}'::jsonb) on conflict (id) do nothing;
insert into hotels (id, doc) values ('HTL-002', '{"id":"HTL-002","name":"أنوار المدينة موفنبيك","city":"المدينة","stars":4,"distanceM":300,"district":"المناخة","phone":"+966 14 820 9000","mapUrl":"","status":"active","notes":"","features":[{"id":"f1","icon":"wifi","text":"واي فاي مجاني"},{"id":"f2","icon":"restaurant","text":"مطعم فاخر"},{"id":"f3","icon":"gym","text":"صالة رياضية"}],"roomTypes":[{"id":"r1","kind":"private","beds":1,"pricePerNight":320},{"id":"r2","kind":"private","beds":2,"pricePerNight":480}],"tasaheelNote":"مثالي للمجموعات القادمة للمدينة المنورة.","reviews":[]}'::jsonb) on conflict (id) do nothing;
insert into hotels (id, doc) values ('HTL-003', '{"id":"HTL-003","name":"سويس أوتيل مكة","city":"مكة","stars":5,"distanceM":250,"district":"أبراج البيت","phone":"+966 12 679 1234","mapUrl":"","status":"active","notes":"","features":[{"id":"f1","icon":"wifi","text":"واي فاي مجاني"},{"id":"f2","icon":"breakfast","text":"إفطار فاخر"},{"id":"f3","icon":"pool","text":"مسبح لا نهائي"},{"id":"f4","icon":"gym","text":"مركز صحي"},{"id":"f5","icon":"spa","text":"سبا ومساج"}],"roomTypes":[{"id":"r1","kind":"private","beds":1,"pricePerNight":650},{"id":"r2","kind":"private","beds":2,"pricePerNight":950}],"tasaheelNote":"إطلالة مباشرة على الكعبة — خيار VIP الأول.","reviews":[{"id":"rv1","name":"سارة","text":"لا يوصف — إطلالة على الكعبة من الغرفة","consent":true},{"id":"rv2","name":"محمد","text":"أفضل تجربة في حياتي","consent":true}]}'::jsonb) on conflict (id) do nothing;
insert into hotels (id, doc) values ('HTL-004', '{"id":"HTL-004","name":"النخبة الاقتصادي","city":"مكة","stars":3,"distanceM":900,"district":"العزيزية","phone":"+966 12 370 5566","mapUrl":"","status":"inactive","notes":"متوقف مؤقتاً لأعمال الصيانة","features":[{"id":"f1","icon":"wifi","text":"واي فاي مجاني"},{"id":"f2","icon":"parking","text":"موقف سيارات"}],"roomTypes":[{"id":"r1","kind":"shared","beds":4,"pricePerNight":75}],"tasaheelNote":"اقتصادي مناسب للميزانيات المحدودة.","reviews":[]}'::jsonb) on conflict (id) do nothing;

-- transports (4)
insert into transports (id, doc) values ('TRN-001', '{"id":"TRN-001","name":"حافلة الحرمين 1","mode":"bus","vehicleType":"حافلة عادية","seats":49,"seatCost":120,"model":"مرسيدس توريزمو","year":"2023","plate":"أ ب ج 1234","driver":"خالد العتيبي","supervisor":"ماجد الزهراني","status":"active","notes":"","features":[{"id":"f1","text":"مكيف هواء"},{"id":"f2","text":"واي فاي مجاني"},{"id":"f3","text":"مقاعد مريحة"},{"id":"f4","text":"ثلاجة مشروبات"}],"reviews":[]}'::jsonb) on conflict (id) do nothing;
insert into transports (id, doc) values ('TRN-002', '{"id":"TRN-002","name":"حافلة الحرمين 2","mode":"bus","vehicleType":"حافلة عادية","seats":49,"seatCost":135,"model":"مان لايونز كوتش","year":"2022","plate":"د هـ و 5678","driver":"سعد القرني","supervisor":"عبدالعزيز الحربي","status":"active","notes":"","features":[{"id":"f1","text":"مكيف هواء"},{"id":"f2","text":"شاشات ترفيه"},{"id":"f3","text":"دورة مياه"},{"id":"f4","text":"مقاعد مريحة"}],"reviews":[]}'::jsonb) on conflict (id) do nothing;
insert into transports (id, doc) values ('TRN-003', '{"id":"TRN-003","name":"سبرينتر VIP","mode":"bus","vehicleType":"حافلة VIP","seats":30,"seatCost":260,"model":"مرسيدس سبرينتر","year":"2024","plate":"ز ح ط 9012","driver":"فهد الشمري","supervisor":"تركي المالكي","status":"active","notes":"","features":[{"id":"f1","text":"مقاعد جلد فاخرة"},{"id":"f2","text":"واي فاي عالي السرعة"},{"id":"f3","text":"خدمة ضيافة"},{"id":"f4","text":"إطلالة بانورامية"}],"reviews":[{"id":"rv1","name":"أحمد","text":"تجربة استثنائية — الراحة على أعلى مستوى","consent":true}]}'::jsonb) on conflict (id) do nothing;
insert into transports (id, doc) values ('TRN-004', '{"id":"TRN-004","name":"رحلة طيران المدينة","mode":"flight","vehicleType":"طيران داخلي","seats":120,"seatCost":480,"model":"طيران ناس","year":"2024","plate":"G9-521","driver":"الكابتن محمد الغامدي","supervisor":"كريم الشهري","status":"active","notes":"","features":[{"id":"f1","text":"مقاعد مريحة"},{"id":"f2","text":"وجبة خفيفة"},{"id":"f3","text":"أمتعة 23 كجم"}],"reviews":[]}'::jsonb) on conflict (id) do nothing;

-- packages (4)
insert into packages (id, doc) values ('PKG-001', '{"id":"PKG-001","name":"عمرة مكة 3 أيام","order":1,"productType":"حافلة","destination":"مكة","audience":"عموم المعتمرين","days":3,"nights":2,"status":"active","marketPrice":150,"recurring":true,"recurDay":"الخميس","startDate":"","transportId":"TRN-001","hotelId":"HTL-001","features":[{"id":"pf1","icon":"guide","text":"مرشد ديني معتمد"},{"id":"pf2","icon":"meal","text":"وجبة ضيافة"},{"id":"pf3","icon":"supervisor","text":"مشرف ثقافي"},{"id":"pf4","icon":"wifi","text":"شاحن لاسلكي"}],"program":[{"id":"ps1","order":1,"icon":"🚌","day":"اليوم الأول","time":"22:00","title":"الانطلاق من الرياض","desc":"التجمع في نقطة الانطلاق وتوزيع أدوات الإحرام"},{"id":"ps2","order":2,"icon":"🕋","day":"اليوم الثاني","time":"06:00","title":"الوصول والعمرة","desc":"أداء مناسك العمرة والطواف والسعي"},{"id":"ps3","order":3,"icon":"🏨","day":"اليوم الثاني","time":"14:00","title":"السكن والراحة","desc":"تسجيل الدخول للفندق وزيارة المشاعر المقدسة"},{"id":"ps4","order":4,"icon":"🔙","day":"اليوم الثالث","time":"20:00","title":"العودة","desc":"التجمع والمغادرة إلى الرياض"}],"roomPrices":[{"id":"rp1","type":"سكن مشترك","persons":1,"perNight":75},{"id":"rp2","type":"غرفة خاصة","persons":2,"perNight":150},{"id":"rp3","type":"غرفة خاصة","persons":3,"perNight":200},{"id":"rp4","type":"غرفة خاصة","persons":4,"perNight":250}],"reviews":[],"notes":"","policies":["إلغاء مجاني قبل 48 ساعة من موعد الرحلة.","لا يوجد استرداد بعد تأكيد الحجز وإصدار التذكرة.","الدفع يتم عبر رابط يرسله موظف الحجزات.","يجب إحضار الهوية الوطنية أو الجواز عند الاستقبال."]}'::jsonb) on conflict (id) do nothing;
insert into packages (id, doc) values ('PKG-002', '{"id":"PKG-002","name":"عمرة مكة 4 أيام","order":2,"productType":"حافلة","destination":"مكة","audience":"العائلات","days":4,"nights":3,"status":"active","marketPrice":175,"recurring":true,"recurDay":"الأربعاء","startDate":"","transportId":"TRN-002","hotelId":"HTL-001","features":[{"id":"pf1","icon":"guide","text":"مرشد ديني معتمد"},{"id":"pf2","icon":"meal","text":"وجبة ضيافة"},{"id":"pf3","icon":"transport","text":"مواصلات داخلية"}],"program":[{"id":"ps1","order":1,"icon":"🚌","day":"اليوم الأول","time":"21:00","title":"الانطلاق","desc":""},{"id":"ps2","order":2,"icon":"🕋","day":"اليوم الثاني","time":"05:30","title":"أداء العمرة","desc":""},{"id":"ps3","order":3,"icon":"🏛️","day":"اليوم الثالث","time":"09:00","title":"زيارة المشاعر","desc":""},{"id":"ps4","order":4,"icon":"🔙","day":"اليوم الرابع","time":"22:00","title":"العودة","desc":""}],"roomPrices":[{"id":"rp1","type":"سكن مشترك","persons":1,"perNight":60},{"id":"rp2","type":"غرفة خاصة","persons":2,"perNight":160},{"id":"rp3","type":"غرفة خاصة","persons":3,"perNight":210}],"reviews":[],"notes":"","policies":["إلغاء مجاني قبل 48 ساعة من موعد الرحلة.","لا يوجد استرداد بعد إصدار التذكرة.","الدفع عبر رابط يرسله الموظف."]}'::jsonb) on conflict (id) do nothing;
insert into packages (id, doc) values ('PKG-003', '{"id":"PKG-003","name":"مكة والمدينة 5 أيام","order":3,"productType":"حافلة","destination":"مكة والمدينة","audience":"عموم المعتمرين","days":5,"nights":4,"status":"active","marketPrice":200,"recurring":false,"recurDay":"","startDate":"2025-08-15","transportId":"TRN-002","hotelId":"HTL-002","features":[{"id":"pf1","icon":"guide","text":"مرشد ديني معتمد"},{"id":"pf2","icon":"meal","text":"وجبتان يومياً"},{"id":"pf3","icon":"supervisor","text":"مشرف ثقافي"},{"id":"pf4","icon":"location","text":"زيارة المدينة المنورة"}],"program":[{"id":"ps1","order":1,"icon":"🚌","day":"اليوم الأول","time":"20:00","title":"الانطلاق إلى مكة","desc":""},{"id":"ps2","order":2,"icon":"🕋","day":"اليوم الثاني","time":"05:00","title":"أداء مناسك العمرة","desc":""},{"id":"ps3","order":3,"icon":"🕌","day":"اليوم الثالث","time":"08:00","title":"التوجه إلى المدينة","desc":""},{"id":"ps4","order":4,"icon":"🏛️","day":"اليوم الرابع","time":"09:00","title":"زيارة المسجد النبوي","desc":""},{"id":"ps5","order":5,"icon":"🔙","day":"اليوم الخامس","time":"18:00","title":"العودة","desc":""}],"roomPrices":[{"id":"rp1","type":"سكن مشترك","persons":1,"perNight":50},{"id":"rp2","type":"غرفة خاصة","persons":2,"perNight":125},{"id":"rp3","type":"غرفة خاصة","persons":3,"perNight":175},{"id":"rp4","type":"غرفة خاصة","persons":4,"perNight":225}],"reviews":[],"notes":"","policies":["إلغاء مجاني قبل 72 ساعة من الرحلة.","تشمل الرحلة وجبتين يومياً.","يجب استيفاء متطلبات التأشيرة قبل الحجز."]}'::jsonb) on conflict (id) do nothing;
insert into packages (id, doc) values ('PKG-004', '{"id":"PKG-004","name":"VIP مكة 4 أيام","order":4,"productType":"رحلة VIP","destination":"مكة","audience":"كبار السن وذوي الاحتياجات الخاصة","days":4,"nights":3,"status":"active","marketPrice":350,"recurring":true,"recurDay":"الجمعة","startDate":"","transportId":"TRN-003","hotelId":"HTL-003","features":[{"id":"pf1","icon":"guide","text":"مرشد ديني معتمد"},{"id":"pf2","icon":"meal","text":"ضيافة فاخرة"},{"id":"pf3","icon":"supervisor","text":"مشرف خاص"},{"id":"pf4","icon":"vip","text":"نقل VIP بين المشاعر"},{"id":"pf5","icon":"view","text":"إطلالة على الكعبة"}],"program":[{"id":"ps1","order":1,"icon":"🚌","day":"اليوم الأول","time":"19:00","title":"الانطلاق VIP","desc":"استقبال فاخر في نقطة التجمع"},{"id":"ps2","order":2,"icon":"🕋","day":"اليوم الثاني","time":"04:00","title":"العمرة في الفجر","desc":"أداء مناسك العمرة مع مرشد خاص"},{"id":"ps3","order":3,"icon":"🏨","day":"اليوم الثالث","time":"10:00","title":"جلسة روحانية","desc":""},{"id":"ps4","order":4,"icon":"🔙","day":"اليوم الرابع","time":"20:00","title":"العودة","desc":""}],"roomPrices":[{"id":"rp1","type":"غرفة خاصة","persons":1,"perNight":250},{"id":"rp2","type":"غرفة خاصة","persons":2,"perNight":400}],"reviews":[{"id":"rv1","name":"فهد","text":"تجربة فريدة لا تُنسى — الاهتمام بالتفاصيل رائع","consent":true}],"notes":"","policies":["خدمة VIP شاملة للمجموعات الصغيرة.","لا يوجد استرداد لحجوزات VIP.","مرشد خاص لكل مجموعة."]}'::jsonb) on conflict (id) do nothing;

-- trips (4)
insert into trips (id, doc) values ('TRP-001', '{"id":"TRP-001","packageId":"PKG-001","transportId":"TRN-001","hotelId":"HTL-001","departureDate":"2025-08-07","returnDate":"2025-08-10","departureTime":"22:00","departurePoint":"أمام مكتب تساهيل — حي العزيزية، الرياض","departureMapUrl":"","seats":49,"bookedSeats":32,"waitingSeats":0,"status":"open","price":300,"drivers":[{"id":"d1","name":"خالد العتيبي","phone":"+966 55 123 4567"}],"settings":{"allowOnlineBooking":true,"manualConfirm":true,"waitlistEnabled":false,"requirePaymentFirst":true,"showTicketAfterConfirm":true,"paymentDeadlineHours":24,"maxPilgrims":10}}'::jsonb) on conflict (id) do nothing;
insert into trips (id, doc) values ('TRP-002', '{"id":"TRP-002","packageId":"PKG-001","transportId":"TRN-001","hotelId":"HTL-001","departureDate":"2025-08-14","returnDate":"2025-08-17","departureTime":"22:00","departurePoint":"أمام مكتب تساهيل — حي العزيزية، الرياض","departureMapUrl":"","seats":49,"bookedSeats":49,"waitingSeats":3,"status":"full","price":300,"drivers":[{"id":"d1","name":"خالد العتيبي","phone":"+966 55 123 4567"},{"id":"d2","name":"فيصل المطيري","phone":"+966 55 987 6543"}],"settings":{"allowOnlineBooking":true,"manualConfirm":true,"waitlistEnabled":true,"requirePaymentFirst":true,"showTicketAfterConfirm":true,"paymentDeadlineHours":24,"maxPilgrims":10}}'::jsonb) on conflict (id) do nothing;
insert into trips (id, doc) values ('TRP-003', '{"id":"TRP-003","packageId":"PKG-003","transportId":"TRN-002","hotelId":"HTL-002","departureDate":"2025-08-13","returnDate":"2025-08-18","departureTime":"21:00","departurePoint":"ساحة النهضة — الرياض","departureMapUrl":"","seats":49,"bookedSeats":18,"waitingSeats":0,"status":"open","price":700,"drivers":[{"id":"d1","name":"سعد القرني","phone":"+966 55 345 6789"}],"settings":{"allowOnlineBooking":true,"manualConfirm":true,"waitlistEnabled":false,"requirePaymentFirst":true,"showTicketAfterConfirm":true,"paymentDeadlineHours":24,"maxPilgrims":10}}'::jsonb) on conflict (id) do nothing;
insert into trips (id, doc) values ('TRP-004', '{"id":"TRP-004","packageId":"PKG-004","transportId":"TRN-003","hotelId":"HTL-003","departureDate":"2025-08-20","returnDate":"2025-08-24","departureTime":"20:00","departurePoint":"مجمع الملك عبدالله — طريق الملك فهد","departureMapUrl":"","seats":30,"bookedSeats":11,"waitingSeats":0,"status":"open","price":1100,"drivers":[{"id":"d1","name":"فهد الشمري","phone":"+966 55 456 7890"}],"settings":{"allowOnlineBooking":true,"manualConfirm":true,"waitlistEnabled":false,"requirePaymentFirst":true,"showTicketAfterConfirm":true,"paymentDeadlineHours":24,"maxPilgrims":6}}'::jsonb) on conflict (id) do nothing;

-- bookings (7)
insert into bookings (id, doc) values ('TSH-1001', '{"id":"TSH-1001","tripId":"TRP-001","clientName":"أحمد محمد العمري","clientPhone":"0501234567","roomType":"غرف خاصة","persons":2,"total":450,"status":"new","paymentStatus":"none","seats":[3,4],"createdAt":"2025-07-01 10:30","staff":"—","sentDate":"—","pilgrims":[{"name":"أحمد محمد العمري","idNumber":"1234567890","nationality":"سعودي","gender":"male","birthDate":"1985-03-15","phone":"0501234567"},{"name":"فاطمة أحمد العمري","idNumber":"2345678901","nationality":"سعودية","gender":"female","birthDate":"1988-07-22","phone":"0501234568"}]}'::jsonb) on conflict (id) do nothing;
insert into bookings (id, doc) values ('TSH-1002', '{"id":"TSH-1002","tripId":"TRP-001","clientName":"سارة عبدالله القحطاني","clientPhone":"0555550012","roomType":"سكن مشترك","persons":1,"total":150,"status":"confirmed","paymentStatus":"verified","payMethod":"تحويل بنكي","txnNo":"TRF-889201","payDate":"2025-06-30","seats":[7],"createdAt":"2025-06-28 09:12","staff":"عادل محمد","sentDate":"2025-06-29","pilgrims":[{"name":"سارة عبدالله القحطاني","idNumber":"1098765432","nationality":"سعودية","gender":"female","birthDate":"1990-01-10","phone":"0555550012"}]}'::jsonb) on conflict (id) do nothing;
insert into bookings (id, doc) values ('TSH-1003', '{"id":"TSH-1003","tripId":"TRP-003","clientName":"عبدالله سعد المطيري","clientPhone":"0533221100","roomType":"غرف خاصة","persons":2,"total":700,"status":"awaiting_payment","paymentStatus":"sent","payMethod":"تابي","txnNo":"—","payDate":"—","seats":[1,2],"createdAt":"2025-06-30 14:45","staff":"عادل محمد","sentDate":"2025-07-01","pilgrims":[{"name":"عبدالله سعد المطيري","idNumber":"1122334455","nationality":"سعودي","gender":"male","birthDate":"1979-11-02","phone":"0533221100"},{"name":"منيرة سعد المطيري","idNumber":"5544332211","nationality":"سعودية","gender":"female","birthDate":"1982-05-19","phone":"0533221101"}]}'::jsonb) on conflict (id) do nothing;
insert into bookings (id, doc) values ('TSH-1004', '{"id":"TSH-1004","tripId":"TRP-004","clientName":"نورة خالد الدوسري","clientPhone":"0566778899","roomType":"غرف خاصة","persons":3,"total":1450,"status":"reviewing","paymentStatus":"none","seats":[],"createdAt":"2025-07-02 08:05","staff":"عادل محمد","sentDate":"—","pilgrims":[{"name":"نورة خالد الدوسري","idNumber":"2211334455","nationality":"سعودية","gender":"female","birthDate":"1986-09-30","phone":"0566778899"},{"name":"خالد نورة الدوسري","idNumber":"2211334456","nationality":"سعودي","gender":"male","birthDate":"2010-05-10","phone":""},{"name":"ريم نورة الدوسري","idNumber":"2211334457","nationality":"سعودية","gender":"female","birthDate":"2014-12-20","phone":""}]}'::jsonb) on conflict (id) do nothing;
insert into bookings (id, doc) values ('TSH-1005', '{"id":"TSH-1005","tripId":"TRP-001","clientName":"محمد سعيد الغامدي","clientPhone":"0599001122","roomType":"غرف خاصة","persons":1,"total":300,"status":"accepted","paymentStatus":"none","seats":[12],"createdAt":"2025-07-02 16:20","staff":"عادل محمد","sentDate":"—","pilgrims":[{"name":"محمد سعيد الغامدي","idNumber":"3322114455","nationality":"سعودي","gender":"male","birthDate":"1975-02-14","phone":"0599001122"}]}'::jsonb) on conflict (id) do nothing;
insert into bookings (id, doc) values ('TSH-1006', '{"id":"TSH-1006","tripId":"TRP-003","clientName":"خالد عمر الشهري","clientPhone":"0561239988","roomType":"غرف خاصة","persons":2,"total":700,"status":"confirmed","paymentStatus":"verified","payMethod":"تمارا","txnNo":"TMR-552310","payDate":"2025-07-03","seats":[20,21],"createdAt":"2025-07-01 12:00","staff":"يوسف علي","sentDate":"2025-07-02","pilgrims":[{"name":"خالد عمر الشهري","idNumber":"1077882299","nationality":"سعودي","gender":"male","birthDate":"1983-04-11","phone":"0561239988"},{"name":"ريم خالد الشهري","idNumber":"1077882300","nationality":"سعودية","gender":"female","birthDate":"2015-08-01","phone":""}]}'::jsonb) on conflict (id) do nothing;
insert into bookings (id, doc) values ('TSH-1007', '{"id":"TSH-1007","tripId":"TRP-004","clientName":"ماجد فيصل العتيبي","clientPhone":"0501119977","roomType":"غرف خاصة","persons":1,"total":480,"status":"awaiting_payment","paymentStatus":"failed","payMethod":"مدى","txnNo":"—","payDate":"—","seats":[],"createdAt":"2025-07-03 09:30","staff":"يوسف علي","sentDate":"2025-07-03","pilgrims":[{"name":"ماجد فيصل العتيبي","idNumber":"1055667788","nationality":"سعودي","gender":"male","birthDate":"1991-12-05","phone":"0501119977"}]}'::jsonb) on conflict (id) do nothing;

-- payments (7)
insert into payments (id, doc) values ('INV-1001', '{"id":"INV-1001","bookingId":"TSH-1001","clientName":"أحمد محمد العمري","clientPhone":"0501234567","packageName":"عمرة مكة 3 أيام","tripDate":"2025-07-10","total":450,"payMethod":"—","payStatus":"none","txnNo":"—","payDate":"—","createdAt":"2025-07-01","roomType":"غرف خاصة"}'::jsonb) on conflict (id) do nothing;
insert into payments (id, doc) values ('INV-1002', '{"id":"INV-1002","bookingId":"TSH-1002","clientName":"سارة عبدالله القحطاني","clientPhone":"0555550012","packageName":"عمرة مكة 3 أيام","tripDate":"2025-07-10","total":150,"payMethod":"تحويل بنكي","payStatus":"verified","txnNo":"TRF-889201","payDate":"2025-06-30","createdAt":"2025-06-28","roomType":"سكن مشترك"}'::jsonb) on conflict (id) do nothing;
insert into payments (id, doc) values ('INV-1003', '{"id":"INV-1003","bookingId":"TSH-1003","clientName":"عبدالله سعد المطيري","clientPhone":"0533221100","packageName":"مكة والمدينة 5 أيام","tripDate":"2025-07-13","total":700,"payMethod":"تابي","payStatus":"sent","txnNo":"—","payDate":"—","createdAt":"2025-06-30","roomType":"غرف خاصة"}'::jsonb) on conflict (id) do nothing;
insert into payments (id, doc) values ('INV-1004', '{"id":"INV-1004","bookingId":"TSH-1004","clientName":"نورة خالد الدوسري","clientPhone":"0566778899","packageName":"VIP مكة 4 أيام","tripDate":"2025-07-20","total":1450,"payMethod":"—","payStatus":"none","txnNo":"—","payDate":"—","createdAt":"2025-07-02","roomType":"غرف خاصة"}'::jsonb) on conflict (id) do nothing;
insert into payments (id, doc) values ('INV-1005', '{"id":"INV-1005","bookingId":"TSH-1005","clientName":"محمد سعيد الغامدي","clientPhone":"0599001122","packageName":"عمرة مكة 3 أيام","tripDate":"2025-07-10","total":300,"payMethod":"—","payStatus":"none","txnNo":"—","payDate":"—","createdAt":"2025-07-02","roomType":"غرف خاصة"}'::jsonb) on conflict (id) do nothing;
insert into payments (id, doc) values ('INV-1006', '{"id":"INV-1006","bookingId":"TSH-1006","clientName":"خالد عمر الشهري","clientPhone":"0561239988","packageName":"مكة والمدينة 5 أيام","tripDate":"2025-07-13","total":700,"payMethod":"تمارا","payStatus":"verified","txnNo":"TMR-552310","payDate":"2025-07-03","createdAt":"2025-07-01","roomType":"غرف خاصة"}'::jsonb) on conflict (id) do nothing;
insert into payments (id, doc) values ('INV-1007', '{"id":"INV-1007","bookingId":"TSH-1007","clientName":"ماجد فيصل العتيبي","clientPhone":"0501119977","packageName":"VIP مكة 4 أيام","tripDate":"2025-07-20","total":480,"payMethod":"مدى","payStatus":"failed","txnNo":"—","payDate":"—","createdAt":"2025-07-03","roomType":"غرف خاصة"}'::jsonb) on conflict (id) do nothing;

-- tickets (2)
insert into tickets (id, doc) values ('TKT-001', '{"ticketNo":"TKT-001","bookingId":"TSH-1002","clientName":"سارة عبدالله القحطاني","clientPhone":"0555550012","packageName":"عمرة مكة 3 أيام","roomType":"سكن مشترك","tripDate":"2025-07-10","tripTime":"22:00","departurePoint":"الرياض — محطة المسافرين","persons":1,"pilgrims":[{"name":"سارة عبدالله القحطاني","idNumber":"1098765432","nationality":"سعودية","gender":"female","birthDate":"1990-01-10","phone":"0555550012"}],"total":150}'::jsonb) on conflict (id) do nothing;
insert into tickets (id, doc) values ('TKT-002', '{"ticketNo":"TKT-002","bookingId":"TSH-1006","clientName":"خالد عمر الشهري","clientPhone":"0561239988","packageName":"مكة والمدينة 5 أيام","roomType":"غرف خاصة","tripDate":"2025-07-13","tripTime":"21:00","departurePoint":"الرياض — محطة المسافرين","persons":2,"pilgrims":[{"name":"خالد عمر الشهري","idNumber":"1077882299","nationality":"سعودي","gender":"male","birthDate":"1983-04-11","phone":"0561239988"},{"name":"ريم خالد الشهري","idNumber":"1077882300","nationality":"سعودية","gender":"female","birthDate":"2015-08-01","phone":""}],"total":700}'::jsonb) on conflict (id) do nothing;

-- beneficiaries (7)
insert into beneficiaries (id, doc) values ('BEN-001', '{"id":"BEN-001","name":"أحمد محمد العمري","phone":"0501234567","idNumber":"1234567890","nationality":"سعودي","gender":"male","birthDate":"1985-03-15","rating":4,"notes":"يفضل السكن الخاص بالدور الأول — لا ينام مبكراً","suspended":false,"bookingIds":["TSH-1001"]}'::jsonb) on conflict (id) do nothing;
insert into beneficiaries (id, doc) values ('BEN-002', '{"id":"BEN-002","name":"سارة عبدالله القحطاني","phone":"0555550012","idNumber":"1098765432","nationality":"سعودية","gender":"female","birthDate":"1990-01-10","rating":5,"notes":"","suspended":false,"bookingIds":["TSH-1002","TSH-1005"]}'::jsonb) on conflict (id) do nothing;
insert into beneficiaries (id, doc) values ('BEN-003', '{"id":"BEN-003","name":"عبدالله سعد المطيري","phone":"0533221100","idNumber":"1122334455","nationality":"سعودي","gender":"male","birthDate":"1979-11-02","rating":3,"notes":"حساس للأصوات — يُفضّل غرفة هادئة","suspended":false,"bookingIds":["TSH-1003"]}'::jsonb) on conflict (id) do nothing;
insert into beneficiaries (id, doc) values ('BEN-004', '{"id":"BEN-004","name":"نورة خالد الدوسري","phone":"0566778899","idNumber":"2211334455","nationality":"سعودية","gender":"female","birthDate":"1986-09-30","rating":0,"notes":"","suspended":false,"bookingIds":["TSH-1004"]}'::jsonb) on conflict (id) do nothing;
insert into beneficiaries (id, doc) values ('BEN-005', '{"id":"BEN-005","name":"محمد سعيد الغامدي","phone":"0599001122","idNumber":"3322114455","nationality":"سعودي","gender":"male","birthDate":"1975-02-14","rating":4,"notes":"","suspended":false,"bookingIds":["TSH-1005"]}'::jsonb) on conflict (id) do nothing;
insert into beneficiaries (id, doc) values ('BEN-006', '{"id":"BEN-006","name":"خالد عمر الشهري","phone":"0561239988","idNumber":"1077882299","nationality":"سعودي","gender":"male","birthDate":"1983-04-11","rating":5,"notes":"عميل مميز — يحجز سنوياً منذ 2022","suspended":false,"bookingIds":["TSH-1006","TSH-1001"]}'::jsonb) on conflict (id) do nothing;
insert into beneficiaries (id, doc) values ('BEN-007', '{"id":"BEN-007","name":"ماجد فيصل العتيبي","phone":"0501119977","idNumber":"1055667788","nationality":"سعودي","gender":"male","birthDate":"1991-12-05","rating":2,"notes":"تأخر في السداد مرتين","suspended":true,"bookingIds":["TSH-1007"]}'::jsonb) on conflict (id) do nothing;

-- users (4)
insert into users (id, doc) values ('U-01', '{"id":"U-01","name":"سالم أحمد","email":"salem@tasahheel.com","role":"مدير النظام","status":"active","lastLogin":"2025-07-05 10:30"}'::jsonb) on conflict (id) do nothing;
insert into users (id, doc) values ('U-02', '{"id":"U-02","name":"عادل محمد","email":"adel@tasahheel.com","role":"موظف","status":"active","lastLogin":"2025-07-05 09:15"}'::jsonb) on conflict (id) do nothing;
insert into users (id, doc) values ('U-03', '{"id":"U-03","name":"يوسف علي","email":"yousef@tasahheel.com","role":"مدير عام","status":"active","lastLogin":"2025-07-04 16:20"}'::jsonb) on conflict (id) do nothing;
insert into users (id, doc) values ('U-04', '{"id":"U-04","name":"فهد الخالد","email":"fahad@tasahheel.com","role":"موظف","status":"inactive","lastLogin":"2025-07-03 11:45"}'::jsonb) on conflict (id) do nothing;

-- support (3)
insert into support (id, doc) values ('SUP-003', '{"id":"SUP-003","category":"تقني — أخطاء في النظام","title":"لا تظهر التذاكر بعد تأكيد الحجز","desc":"","priority":"عاجل","status":"resolved","date":"2025-06-28"}'::jsonb) on conflict (id) do nothing;
insert into support (id, doc) values ('SUP-002', '{"id":"SUP-002","category":"مالي — فواتير وتحصيل","title":"مشكلة في ربط بوابة تمارا","desc":"","priority":"متوسط","status":"reviewing","date":"2025-07-01"}'::jsonb) on conflict (id) do nothing;
insert into support (id, doc) values ('SUP-001', '{"id":"SUP-001","category":"محتوى — تعديل النصوص","title":"تعديل وصف الباقة VIP","desc":"","priority":"منخفض","status":"sent","date":"2025-07-03"}'::jsonb) on conflict (id) do nothing;

